function [T, problematic_train, ...
    problematic_test] = analysis_GP_channel(SURF_points_train, years_train, ...
    SURF_points_test, years_test)
% Performs an analysis of the Gaussian Process for a color channel
% In: SURF_points_train ... n x 20 matrix, n the number of paintings analized
%     years ... n x 1 vector, vector with the years of the paintings
%     SURF_points_test ... m x 20 matrix, m the number of test paintings
%     years_test ... m x 1 vector, vector with the years of the test paintings
%     channel name ... string name of the channel ('Red', 'Green', 'Blue')
% Analysis made:
%      - fit naively a Gaussian process (standard Matlab)

% 

T = zeros(18, 15);

% NOW WE CHANGE SOME PARAMETERS: Kernel function + optimization method


% exponential kernel + quasinewton
[T(1, :), problematic_training_expo_quasi, ...
    problematic_testing_expo_quasi] = fitDiff_stats(SURF_points_train, years_train, SURF_points_test, years_test, 'exponential', 'quasinewton');

% exponential kernel + lbfgs
[T(2, :), problematic_training_expo_lbfgs, ...
    problematic_testing_expo_lbfgs] = fitDiff_stats(SURF_points_train, years_train, SURF_points_test, years_test, 'exponential', 'lbfgs');


% Matern kernel with parameter 3/2 + quasinewton
[T(3, :), problematic_training_matern32_quasi, ...
    problematic_testing_matern32_quasi] = fitDiff_stats(SURF_points_train, years_train, SURF_points_test, years_test, 'matern32', 'quasinewton');

% Matern kernel with parameter 3/2 + lbfgs
[T(4, :), problematic_training_matern32_lbfgs, ...
    problematic_testing_matern32_lbfgs] = fitDiff_stats(SURF_points_train, years_train, SURF_points_test, years_test, 'matern32', 'lbfgs');


% Matern kernel with parameter 5/2 + quasinewton
[T(5, :), problematic_training_matern52_quasi, ...
    problematic_testing_matern52_quasi] = fitDiff_stats(SURF_points_train, years_train, SURF_points_test, years_test, 'matern52', 'quasinewton');

% Matern kernel with parameter 5/2 + lbfgs
[T(6, :), problematic_training_matern52_lbfgs, ...
    problematic_testing_matern52_lbfgs] = fitDiff_stats(SURF_points_train, years_train, SURF_points_test, years_test, 'matern52', 'lbfgs');


% Rational quadratic kernel + quasinewton
[T(7, :), problematic_training_rationalquadratic_quasi, ...
    problematic_testing_rationalquadratic_quasi] = fitDiff_stats(SURF_points_train, years_train, SURF_points_test, years_test, 'rationalquadratic', 'quasinewton');

% Rational quadratic kernel + lbfgs
[T(8, :), problematic_training_rationalquadratic_lbfgs, ...
    problematic_testing_rationalquadratic_lbfgs] = fitDiff_stats(SURF_points_train, years_train, SURF_points_test, years_test, 'rationalquadratic', 'lbfgs');


% Exponential kernel with a separate length scale per predictor + quasinewton
[T(9, :), problematic_training_ardexponential_quasi, ...
    problematic_testing_ardexponential_quasi] = fitDiff_stats(SURF_points_train, years_train, SURF_points_test, years_test, 'ardexponential', 'quasinewton');

% Exponential kernel with a separate length scale per predictor + lbfgs
[T(10, :), problematic_training_ardexponential_lbfgs, ...
    problematic_testing_ardexponential_lbfgs] = fitDiff_stats(SURF_points_train, years_train, SURF_points_test, years_test, 'ardexponential', 'lbfgs');


% Squared exponential kernel with a separate length scale per predictor +
% quasinewton
[T(11, :), problematic_training_ardsquaredexponential_quasi, ...
    problematic_testing_ardsquaredexponential_quasi] = fitDiff_stats(SURF_points_train, years_train, SURF_points_test, years_test, 'ardsquaredexponential', 'quasinewton');

% Squared exponential kernel with a separate length scale per predictor +
% lbfgs
[T(12, :), problematic_training_ardsquaredexponential_lbfgs, ...
    problematic_testing_ardsquaredexponential_lbfgs] = fitDiff_stats(SURF_points_train, years_train, SURF_points_test, years_test, 'ardsquaredexponential', 'lbfgs');


% Matern kernel with parameter 3/2 and a separate length scale per
% predictor + quasinewton 
[T(13, :), problematic_training_ardmatern32_quasi, ...
    problematic_testing_ardmatern32_quasi] = fitDiff_stats(SURF_points_train, years_train, SURF_points_test, years_test, 'ardmatern32', 'quasinewton');

% Matern kernel with parameter 3/2 and a separate length scale per
% predictor + lbfgs
[T(14, :), problematic_training_ardmatern32_lbfgs, ...
    problematic_testing_ardmatern32_lbfgs] = fitDiff_stats(SURF_points_train, years_train, SURF_points_test, years_test, 'ardmatern32', 'lbfgs');


% Matern kernel with parameter 5/2 and a separate length scale per
% predictor + quasinewton
[T(15, :), problematic_training_ardmatern52_quasi, ...
    problematic_testing_ardmatern52_quasi] = fitDiff_stats(SURF_points_train, years_train, SURF_points_test, years_test, 'ardmatern52', 'quasinewton');

% Matern kernel with parameter 5/2 and a separate length scale per
% predictor + lbfgs
[T(16, :), problematic_training_ardmatern52_lbfgs, ...
    problematic_testing_ardmatern52_lbfgs] = fitDiff_stats(SURF_points_train, years_train, SURF_points_test, years_test, 'ardmatern52', 'lbfgs');


% Rational quadratic kernel with a separate length scale per predictor   +
% quasinewton
[T(17, :), problematic_training_ardrationalquadratic_quasi, ...
    problematic_testing_ardrationalquadratic_quasi] = fitDiff_stats(SURF_points_train, years_train, SURF_points_test, years_test, 'ardrationalquadratic', 'quasinewton');

% Rational quadratic kernel with a separate length scale per predictor   +
% lbfgs
[T(18, :), problematic_training_ardrationalquadratic_lbfgs, ...
    problematic_testing_ardrationalquadratic_lbfgs] = fitDiff_stats(SURF_points_train, years_train, SURF_points_test, years_test, 'ardrationalquadratic', 'lbfgs');


problematic_train = intersect( problematic_training_expo_quasi', ...
    [problematic_training_expo_lbfgs', problematic_training_matern32_quasi', ...
    problematic_training_matern32_lbfgs', problematic_training_matern52_quasi', ...
    problematic_training_matern52_lbfgs', problematic_training_rationalquadratic_quasi',  ...
    problematic_training_rationalquadratic_lbfgs', ...
    problematic_training_ardexponential_quasi', ...
    problematic_training_ardexponential_lbfgs', ...
    problematic_training_ardsquaredexponential_quasi', ...
    problematic_training_ardsquaredexponential_lbfgs', ...
    problematic_training_ardmatern32_quasi', ...
    problematic_training_ardmatern32_lbfgs', ...
    problematic_training_ardmatern52_quasi', ...
    problematic_training_ardmatern52_lbfgs', ... 
    problematic_training_ardrationalquadratic_quasi', ...
    problematic_training_ardrationalquadratic_lbfgs'] );

problematic_test = intersect( problematic_testing_expo_quasi', ...
    [problematic_testing_expo_lbfgs', problematic_testing_matern32_quasi', ...
    problematic_testing_matern32_lbfgs', problematic_testing_matern52_quasi', ...
    problematic_testing_matern52_lbfgs', problematic_testing_rationalquadratic_quasi',  ...
    problematic_testing_rationalquadratic_lbfgs', ...
    problematic_testing_ardexponential_quasi', ...
    problematic_testing_ardexponential_lbfgs', ...
    problematic_testing_ardsquaredexponential_quasi', ...
    problematic_testing_ardsquaredexponential_lbfgs', ...
    problematic_testing_ardmatern32_quasi', ...
    problematic_testing_ardmatern32_lbfgs', ...
    problematic_testing_ardmatern52_quasi', ...
    problematic_testing_ardmatern52_lbfgs', ... 
    problematic_testing_ardrationalquadratic_quasi', ...
    problematic_testing_ardrationalquadratic_lbfgs'] );

end


